// Copyright Viklauverk AB 2021
// Generated by "make logmodules"
package com.viklauverk.eventbtools.core;
public enum LogModuleNames
{
canvas,
canvaslineformatting,
cmdline,
codegen,
console,
context,
doc,
docgen,
docmod,
edk,
event,
formula,
htmq,
machine,
main,
parser,
pattern,
renderformula,
symbols,
sys,
tex,
typing,
unicode,
util,
}
